### ISSUE TITLE
嘗試召喚時後台顯示錯誤

### ISSUE THREAD

**Issue by dirtTW** [Passion-Never-Dissipate/World_Eater_Manage#2]
```
[Server] [07:38:49] [Server thread/INFO]: <dirtTW> !!we spawn -175 -86 94 197 0 6
Exception in thread we_spawn:
Traceback (most recent call last):
  File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapp
ed_target
    raise e from None
  File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapp
ed_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\world_eater_manage-1.1.0.mcdr\world_eater_manage\__init__.py", line 202, in spawn_bot
  File "plugins\world_eater_manage-1.1.0.mcdr\world_eater_manage\__init__.py", line 53, in __init__
  File "plugins\world_eater_manage-1.1.0.mcdr\world_eater_manage\__init__.py", line 121, in sort
KeyError: 'default'
```

第一次使用有成功召喚 之後就一直顯示錯誤

**Comment by ailixiyaX** [comment]
+1 我在使用!!we clear功能后出现了该错误，之前没有

**Comment by FRUITS-CANDY** [comment]
> ```
> [Server] [07:38:49] [Server thread/INFO]: <dirtTW> !!we spawn -175 -86 94 197 0 6
> Exception in thread we_spawn:
> Traceback (most recent call last):
>   File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
>     self.run()
>   File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapp
> ed_target
>     raise e from None
>   File "C:\Users\pp490\AppData\Local\Programs\Python\Python312\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapp
> ed_target
>     self.__return_value = target(*args_, **kwargs_)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "plugins\world_eater_manage-1.1.0.mcdr\world_eater_manage\__init__.py", line 202, in spawn_bot
>   File "plugins\world_eater_manage-1.1.0.mcdr\world_eater_manage\__init__.py", line 53, in __init__
>   File "plugins\world_eater_manage-1.1.0.mcdr\world_eater_manage\__init__.py", line 121, in sort
> KeyError: 'default'
> ```
> 
> 第一次使用有成功召喚 之後就一直顯示錯誤

已解决，请尝试最新版本1.2.0

**Comment by FRUITS-CANDY** [comment]
> 已解决，请尝试最新版本1.2.0

**Comment by FRUITS-CANDY** [comment]
> +1 我在使用!!we clear功能后出现了该错误，之前没有

已解决，请尝试最新版本1.2.0
